title: "ITP 438 - Fall 2022"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true
footer_content: "Except where otherwise noted, this website is &copy; 2021 Sanjay Madhav and is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>License</a>."
